version: '3.8'

services:
  app:
    image: helloworld-app
    container_name: hello_world_app
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dummydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
